name: Frontendend - Test & Deploy

on:
  workflow_dispatch:
  repository_dispatch:
    types: [backend-deployed]
jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: react-build
          path: ./frontend/build

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
        with:
          enablement: true

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          path: ./frontend/build
